{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "base-service.fullname" . }}
  namespace: {{ .Values.monitoring.namespace | default .Release.Namespace }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
    {{- with .Values.monitoring.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "base-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | default "10s" }}
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
        - targetLabel: cluster
          replacement: {{ .Values.monitoring.clusterName | default "logisticos" }}
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "go_.*"
          action: drop
{{- end }}
